import Foundation

// Generated by scripts/gen-parity-fixtures.py — do not edit by hand.
// Shared input for the C self-test and the Swift parity self-test, so that a
// difference between the two implementations cannot be masked by a difference
// in what they were fed.


enum CoreParityFixtures {
    static let mediaBase = "https://origin.example.com/live/hls/media.m3u8"
    static let media = "#EXTM3U\n#EXT-X-VERSION:6\n#EXT-X-TARGETDURATION:4\n#EXT-X-MEDIA-SEQUENCE:42\n#EXT-X-KEY:METHOD=AES-128,URI=\"key.bin\",IV=0x0123456789abcdef0123456789abcdef\n#EXT-X-MAP:URI=\"init.mp4\"\n\n#EXTINF:4.000,\nseg1.m4s\n#EXTINF:4.000,\n./sub/seg2.m4s\n#EXTINF:4.000,\n../up/seg3.m4s\n#EXTINF:4.000,\n/rooted/seg4.m4s\n#EXTINF:4.000,\nhttps://cdn.example.com/abs/seg5.m4s\n#EXTINF:4.000,\n  spaced/seg6.m4s  \n#EXTINF:4.000,\nseg 7.m4s\n#EXT-X-ENDLIST\n"

    static let mediaPlainBase = "https://origin.example.com/a/b/c.m3u8"
    static let mediaPlain = "#EXTM3U\n#EXTINF:2.000,\ns0.ts\n#EXT-X-KEY:METHOD=AES-128,URI=\"https://keys.example.com/k?id=1\"\n#EXTINF:2.000,\ns1.ts\n"

    static let masterBase = "https://origin.example.com/live/master.m3u8"
    static let master = "#EXTM3U\n#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID=\"aac\",NAME=\"English\",LANGUAGE=\"en\",DEFAULT=YES,URI=\"audio/en.m3u8\"\n#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID=\"aac\",NAME=\"Commentary, extended\",URI=\"audio/cm.m3u8\"\n#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID=\"subs\",NAME=\"English\",URI=\"subs/en.m3u8\"\n#EXT-X-STREAM-INF:BANDWIDTH=1280000,RESOLUTION=1280x720,CODECS=\"avc1.4d401f,mp4a.40.2\",AUDIO=\"aac\"\n720p/index.m3u8\n#EXT-X-STREAM-INF:BANDWIDTH=2560000,RESOLUTION=1920x1080,CODECS=\"avc1.640028,mp4a.40.2\",AUDIO=\"aac\"\nhttps://cdn.example.com/1080p/index.m3u8\n#EXT-X-STREAM-INF:BANDWIDTH=400000\naudio-only.m3u8\n"

    static let masterTailBase = "https://origin.example.com/live/master.m3u8"
    static let masterTail = "#EXTM3U\n#EXT-X-STREAM-INF:BANDWIDTH=100"

    static let playlists: [(name: String, base: String, text: String)] = [
        ("media", mediaBase, media),
        ("media_plain", mediaPlainBase, mediaPlain),
        ("master", masterBase, master),
        ("master_tail", masterTailBase, masterTail),
    ]

    static let ffmpegCases: [(name: String, inputs: FFmpegResident.Inputs)] = [
        ("ts-hls", FFmpegResident.Inputs(
            ffmpegPath: "/usr/local/bin/ffmpeg",
            sourceURL: "https://origin.example.com/live/stream.m3u8",
            kind: "m3u8",
            inputMode: "ffmpegTsHls",
            outputMode: "hls",
            outputTarget: "",
            decryptionKeys: "",
            headers: "",
            proxy: "",
            segmentUrlParams: "",
            representationIds: [],
            representationTypes: [:],
            tempDir: URL(fileURLWithPath: "/tmp/restreamair-fixture"),
            outputPlaylist: URL(fileURLWithPath: "/tmp/restreamair-fixture/live.m3u8"),
            playlistSegments: 6,
            segmentSeconds: 4
        )),
        ("fmp4-hls-with-headers-and-key", FFmpegResident.Inputs(
            ffmpegPath: "/usr/local/bin/ffmpeg",
            sourceURL: "https://origin.example.com/live/stream.mpd",
            kind: "mpd",
            inputMode: "ffmpegFmp4Hls",
            outputMode: "hls",
            outputTarget: "",
            decryptionKeys: "  \nabcdef0123456789abcdef0123456789:00112233445566778899aabbccddeeff\n",
            headers: "User-Agent: ReStreamAir/1.0\n\n  Referer: https://example.com  \n",
            proxy: "http://127.0.0.1:8888",
            segmentUrlParams: " ?token=abc&region=eu ",
            representationIds: [],
            representationTypes: [:],
            tempDir: URL(fileURLWithPath: "/tmp/restreamair-fixture"),
            outputPlaylist: URL(fileURLWithPath: "/tmp/restreamair-fixture/live.m3u8"),
            playlistSegments: 6,
            segmentSeconds: 4
        )),
        ("multi-ts-hls", FFmpegResident.Inputs(
            ffmpegPath: "/usr/local/bin/ffmpeg",
            sourceURL: "https://origin.example.com/live/stream.mpd",
            kind: "mpd",
            inputMode: "ffmpegMultiTsHls",
            outputMode: "hls",
            outputTarget: "",
            decryptionKeys: "00112233445566778899aabbccddeeff",
            headers: "",
            proxy: "",
            segmentUrlParams: "",
            representationIds: ["v1", "v2", "a1"],
            representationTypes: ["v1": "video", "v2": "video", "a1": "audio"],
            tempDir: URL(fileURLWithPath: "/tmp/restreamair-fixture"),
            outputPlaylist: URL(fileURLWithPath: "/tmp/restreamair-fixture/live.m3u8"),
            playlistSegments: 6,
            segmentSeconds: 4
        )),
        ("multi-ts-hls-single-video", FFmpegResident.Inputs(
            ffmpegPath: "/usr/local/bin/ffmpeg",
            sourceURL: "https://origin.example.com/live/stream.mpd",
            kind: "mpd",
            inputMode: "ffmpegMultiTsHls",
            outputMode: "hls",
            outputTarget: "",
            decryptionKeys: "",
            headers: "",
            proxy: "",
            segmentUrlParams: "",
            representationIds: ["v1", "a1"],
            representationTypes: ["v1": "video", "a1": "audio"],
            tempDir: URL(fileURLWithPath: "/tmp/restreamair-fixture"),
            outputPlaylist: URL(fileURLWithPath: "/tmp/restreamair-fixture/live.m3u8"),
            playlistSegments: 6,
            segmentSeconds: 4
        )),
        ("resident-srt-server-bare-port", FFmpegResident.Inputs(
            ffmpegPath: "/usr/local/bin/ffmpeg",
            sourceURL: "https://origin.example.com/live/stream.mpd",
            kind: "mpd",
            inputMode: "ffmpegResident",
            outputMode: "srtServer",
            outputTarget: "9100",
            decryptionKeys: "",
            headers: "",
            proxy: "",
            segmentUrlParams: "",
            representationIds: [],
            representationTypes: [:],
            tempDir: URL(fileURLWithPath: "/tmp/restreamair-fixture"),
            outputPlaylist: URL(fileURLWithPath: "/tmp/restreamair-fixture/live.m3u8"),
            playlistSegments: 6,
            segmentSeconds: 4
        )),
        ("resident-srt-server-empty-port", FFmpegResident.Inputs(
            ffmpegPath: "/usr/local/bin/ffmpeg",
            sourceURL: "https://origin.example.com/live/stream.mpd",
            kind: "mpd",
            inputMode: "ffmpegResident",
            outputMode: "srtServer",
            outputTarget: "",
            decryptionKeys: "",
            headers: "",
            proxy: "",
            segmentUrlParams: "",
            representationIds: [],
            representationTypes: [:],
            tempDir: URL(fileURLWithPath: "/tmp/restreamair-fixture"),
            outputPlaylist: URL(fileURLWithPath: "/tmp/restreamair-fixture/live.m3u8"),
            playlistSegments: 6,
            segmentSeconds: 4
        )),
        ("resident-udp-push", FFmpegResident.Inputs(
            ffmpegPath: "/usr/local/bin/ffmpeg",
            sourceURL: "rtmp://origin.example.com/live/stream",
            kind: "mpd",
            inputMode: "ffmpegResident",
            outputMode: "udpSrt",
            outputTarget: "udp://239.0.0.1:1234?pkt_size=1316",
            decryptionKeys: "",
            headers: "",
            proxy: "",
            segmentUrlParams: "ignored=1",
            representationIds: [],
            representationTypes: [:],
            tempDir: URL(fileURLWithPath: "/tmp/restreamair-fixture"),
            outputPlaylist: URL(fileURLWithPath: "/tmp/restreamair-fixture/live.m3u8"),
            playlistSegments: 6,
            segmentSeconds: 4
        )),
        ("resident-custom-quoted", FFmpegResident.Inputs(
            ffmpegPath: "/usr/local/bin/ffmpeg",
            sourceURL: "https://origin.example.com/live/stream.m3u8?a=1",
            kind: "m3u8",
            inputMode: "ffmpegResident",
            outputMode: "custom",
            outputTarget: "-f flv 'rtmp://a.example.com/app/key with spaces' -metadata title=\"My Stream\"",
            decryptionKeys: ":deadbeefdeadbeefdeadbeefdeadbeef",
            headers: "",
            proxy: "",
            segmentUrlParams: "&more=2",
            representationIds: [],
            representationTypes: [:],
            tempDir: URL(fileURLWithPath: "/tmp/restreamair-fixture"),
            outputPlaylist: URL(fileURLWithPath: "/tmp/restreamair-fixture/live.m3u8"),
            playlistSegments: 6,
            segmentSeconds: 4
        )),
    ]
}
