# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.4

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/moon/Library/Mobile Documents/com~apple~CloudDocs/g_g/ReStreamAir"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/moon/Library/Mobile Documents/com~apple~CloudDocs/g_g/ReStreamAir"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/moon/Library/Mobile Documents/com~apple~CloudDocs/g_g/ReStreamAir/CMakeFiles" "/Users/moon/Library/Mobile Documents/com~apple~CloudDocs/g_g/ReStreamAir//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/moon/Library/Mobile Documents/com~apple~CloudDocs/g_g/ReStreamAir/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named restream_base

# Build rule for target.
restream_base: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 restream_base
.PHONY : restream_base

# fast build rule for target.
restream_base/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/build
.PHONY : restream_base/fast

#=============================================================================
# Target rules for targets named restream_core

# Build rule for target.
restream_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 restream_core
.PHONY : restream_core

# fast build rule for target.
restream_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_core.dir/build.make CMakeFiles/restream_core.dir/build
.PHONY : restream_core/fast

#=============================================================================
# Target rules for targets named restream_selftest

# Build rule for target.
restream_selftest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 restream_selftest
.PHONY : restream_selftest

# fast build rule for target.
restream_selftest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_selftest.dir/build.make CMakeFiles/restream_selftest.dir/build
.PHONY : restream_selftest/fast

#=============================================================================
# Target rules for targets named restreamair-server

# Build rule for target.
restreamair-server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 restreamair-server
.PHONY : restreamair-server

# fast build rule for target.
restreamair-server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restreamair-server.dir/build.make CMakeFiles/restreamair-server.dir/build
.PHONY : restreamair-server/fast

apps/server/main.o: apps/server/main.cpp.o
.PHONY : apps/server/main.o

# target to build an object file
apps/server/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restreamair-server.dir/build.make CMakeFiles/restreamair-server.dir/apps/server/main.cpp.o
.PHONY : apps/server/main.cpp.o

apps/server/main.i: apps/server/main.cpp.i
.PHONY : apps/server/main.i

# target to preprocess a source file
apps/server/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restreamair-server.dir/build.make CMakeFiles/restreamair-server.dir/apps/server/main.cpp.i
.PHONY : apps/server/main.cpp.i

apps/server/main.s: apps/server/main.cpp.s
.PHONY : apps/server/main.s

# target to generate assembly for a file
apps/server/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restreamair-server.dir/build.make CMakeFiles/restreamair-server.dir/apps/server/main.cpp.s
.PHONY : apps/server/main.cpp.s

apps/server/net.o: apps/server/net.c.o
.PHONY : apps/server/net.o

# target to build an object file
apps/server/net.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restreamair-server.dir/build.make CMakeFiles/restreamair-server.dir/apps/server/net.c.o
.PHONY : apps/server/net.c.o

apps/server/net.i: apps/server/net.c.i
.PHONY : apps/server/net.i

# target to preprocess a source file
apps/server/net.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restreamair-server.dir/build.make CMakeFiles/restreamair-server.dir/apps/server/net.c.i
.PHONY : apps/server/net.c.i

apps/server/net.s: apps/server/net.c.s
.PHONY : apps/server/net.s

# target to generate assembly for a file
apps/server/net.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restreamair-server.dir/build.make CMakeFiles/restreamair-server.dir/apps/server/net.c.s
.PHONY : apps/server/net.c.s

apps/server/probe.o: apps/server/probe.c.o
.PHONY : apps/server/probe.o

# target to build an object file
apps/server/probe.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restreamair-server.dir/build.make CMakeFiles/restreamair-server.dir/apps/server/probe.c.o
.PHONY : apps/server/probe.c.o

apps/server/probe.i: apps/server/probe.c.i
.PHONY : apps/server/probe.i

# target to preprocess a source file
apps/server/probe.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restreamair-server.dir/build.make CMakeFiles/restreamair-server.dir/apps/server/probe.c.i
.PHONY : apps/server/probe.c.i

apps/server/probe.s: apps/server/probe.c.s
.PHONY : apps/server/probe.s

# target to generate assembly for a file
apps/server/probe.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restreamair-server.dir/build.make CMakeFiles/restreamair-server.dir/apps/server/probe.c.s
.PHONY : apps/server/probe.c.s

apps/server/rs_dash.o: apps/server/rs_dash.c.o
.PHONY : apps/server/rs_dash.o

# target to build an object file
apps/server/rs_dash.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restreamair-server.dir/build.make CMakeFiles/restreamair-server.dir/apps/server/rs_dash.c.o
.PHONY : apps/server/rs_dash.c.o

apps/server/rs_dash.i: apps/server/rs_dash.c.i
.PHONY : apps/server/rs_dash.i

# target to preprocess a source file
apps/server/rs_dash.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restreamair-server.dir/build.make CMakeFiles/restreamair-server.dir/apps/server/rs_dash.c.i
.PHONY : apps/server/rs_dash.c.i

apps/server/rs_dash.s: apps/server/rs_dash.c.s
.PHONY : apps/server/rs_dash.s

# target to generate assembly for a file
apps/server/rs_dash.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restreamair-server.dir/build.make CMakeFiles/restreamair-server.dir/apps/server/rs_dash.c.s
.PHONY : apps/server/rs_dash.c.s

core/deps/cJSON.o: core/deps/cJSON.c.o
.PHONY : core/deps/cJSON.o

# target to build an object file
core/deps/cJSON.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/deps/cJSON.c.o
.PHONY : core/deps/cJSON.c.o

core/deps/cJSON.i: core/deps/cJSON.c.i
.PHONY : core/deps/cJSON.i

# target to preprocess a source file
core/deps/cJSON.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/deps/cJSON.c.i
.PHONY : core/deps/cJSON.c.i

core/deps/cJSON.s: core/deps/cJSON.c.s
.PHONY : core/deps/cJSON.s

# target to generate assembly for a file
core/deps/cJSON.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/deps/cJSON.c.s
.PHONY : core/deps/cJSON.c.s

core/deps/mongoose.o: core/deps/mongoose.c.o
.PHONY : core/deps/mongoose.o

# target to build an object file
core/deps/mongoose.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_core.dir/build.make CMakeFiles/restream_core.dir/core/deps/mongoose.c.o
.PHONY : core/deps/mongoose.c.o

core/deps/mongoose.i: core/deps/mongoose.c.i
.PHONY : core/deps/mongoose.i

# target to preprocess a source file
core/deps/mongoose.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_core.dir/build.make CMakeFiles/restream_core.dir/core/deps/mongoose.c.i
.PHONY : core/deps/mongoose.c.i

core/deps/mongoose.s: core/deps/mongoose.c.s
.PHONY : core/deps/mongoose.s

# target to generate assembly for a file
core/deps/mongoose.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_core.dir/build.make CMakeFiles/restream_core.dir/core/deps/mongoose.c.s
.PHONY : core/deps/mongoose.c.s

core/src/aes.o: core/src/aes.c.o
.PHONY : core/src/aes.o

# target to build an object file
core/src/aes.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/aes.c.o
.PHONY : core/src/aes.c.o

core/src/aes.i: core/src/aes.c.i
.PHONY : core/src/aes.i

# target to preprocess a source file
core/src/aes.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/aes.c.i
.PHONY : core/src/aes.c.i

core/src/aes.s: core/src/aes.c.s
.PHONY : core/src/aes.s

# target to generate assembly for a file
core/src/aes.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/aes.c.s
.PHONY : core/src/aes.c.s

core/src/audio_delay.o: core/src/audio_delay.c.o
.PHONY : core/src/audio_delay.o

# target to build an object file
core/src/audio_delay.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/audio_delay.c.o
.PHONY : core/src/audio_delay.c.o

core/src/audio_delay.i: core/src/audio_delay.c.i
.PHONY : core/src/audio_delay.i

# target to preprocess a source file
core/src/audio_delay.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/audio_delay.c.i
.PHONY : core/src/audio_delay.c.i

core/src/audio_delay.s: core/src/audio_delay.c.s
.PHONY : core/src/audio_delay.s

# target to generate assembly for a file
core/src/audio_delay.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/audio_delay.c.s
.PHONY : core/src/audio_delay.c.s

core/src/auth.o: core/src/auth.c.o
.PHONY : core/src/auth.o

# target to build an object file
core/src/auth.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/auth.c.o
.PHONY : core/src/auth.c.o

core/src/auth.i: core/src/auth.c.i
.PHONY : core/src/auth.i

# target to preprocess a source file
core/src/auth.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/auth.c.i
.PHONY : core/src/auth.c.i

core/src/auth.s: core/src/auth.c.s
.PHONY : core/src/auth.s

# target to generate assembly for a file
core/src/auth.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/auth.c.s
.PHONY : core/src/auth.c.s

core/src/cdm.o: core/src/cdm.c.o
.PHONY : core/src/cdm.o

# target to build an object file
core/src/cdm.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/cdm.c.o
.PHONY : core/src/cdm.c.o

core/src/cdm.i: core/src/cdm.c.i
.PHONY : core/src/cdm.i

# target to preprocess a source file
core/src/cdm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/cdm.c.i
.PHONY : core/src/cdm.c.i

core/src/cdm.s: core/src/cdm.c.s
.PHONY : core/src/cdm.s

# target to generate assembly for a file
core/src/cdm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/cdm.c.s
.PHONY : core/src/cdm.c.s

core/src/cenc.o: core/src/cenc.c.o
.PHONY : core/src/cenc.o

# target to build an object file
core/src/cenc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/cenc.c.o
.PHONY : core/src/cenc.c.o

core/src/cenc.i: core/src/cenc.c.i
.PHONY : core/src/cenc.i

# target to preprocess a source file
core/src/cenc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/cenc.c.i
.PHONY : core/src/cenc.c.i

core/src/cenc.s: core/src/cenc.c.s
.PHONY : core/src/cenc.s

# target to generate assembly for a file
core/src/cenc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/cenc.c.s
.PHONY : core/src/cenc.c.s

core/src/common.o: core/src/common.c.o
.PHONY : core/src/common.o

# target to build an object file
core/src/common.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/common.c.o
.PHONY : core/src/common.c.o

core/src/common.i: core/src/common.c.i
.PHONY : core/src/common.i

# target to preprocess a source file
core/src/common.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/common.c.i
.PHONY : core/src/common.c.i

core/src/common.s: core/src/common.c.s
.PHONY : core/src/common.s

# target to generate assembly for a file
core/src/common.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/common.c.s
.PHONY : core/src/common.c.s

core/src/crypto.o: core/src/crypto.c.o
.PHONY : core/src/crypto.o

# target to build an object file
core/src/crypto.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/crypto.c.o
.PHONY : core/src/crypto.c.o

core/src/crypto.i: core/src/crypto.c.i
.PHONY : core/src/crypto.i

# target to preprocess a source file
core/src/crypto.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/crypto.c.i
.PHONY : core/src/crypto.c.i

core/src/crypto.s: core/src/crypto.c.s
.PHONY : core/src/crypto.s

# target to generate assembly for a file
core/src/crypto.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/crypto.c.s
.PHONY : core/src/crypto.c.s

core/src/ffargs.o: core/src/ffargs.c.o
.PHONY : core/src/ffargs.o

# target to build an object file
core/src/ffargs.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/ffargs.c.o
.PHONY : core/src/ffargs.c.o

core/src/ffargs.i: core/src/ffargs.c.i
.PHONY : core/src/ffargs.i

# target to preprocess a source file
core/src/ffargs.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/ffargs.c.i
.PHONY : core/src/ffargs.c.i

core/src/ffargs.s: core/src/ffargs.c.s
.PHONY : core/src/ffargs.s

# target to generate assembly for a file
core/src/ffargs.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/ffargs.c.s
.PHONY : core/src/ffargs.c.s

core/src/hls_decrypt.o: core/src/hls_decrypt.c.o
.PHONY : core/src/hls_decrypt.o

# target to build an object file
core/src/hls_decrypt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/hls_decrypt.c.o
.PHONY : core/src/hls_decrypt.c.o

core/src/hls_decrypt.i: core/src/hls_decrypt.c.i
.PHONY : core/src/hls_decrypt.i

# target to preprocess a source file
core/src/hls_decrypt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/hls_decrypt.c.i
.PHONY : core/src/hls_decrypt.c.i

core/src/hls_decrypt.s: core/src/hls_decrypt.c.s
.PHONY : core/src/hls_decrypt.s

# target to generate assembly for a file
core/src/hls_decrypt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/hls_decrypt.c.s
.PHONY : core/src/hls_decrypt.c.s

core/src/json.o: core/src/json.c.o
.PHONY : core/src/json.o

# target to build an object file
core/src/json.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/json.c.o
.PHONY : core/src/json.c.o

core/src/json.i: core/src/json.c.i
.PHONY : core/src/json.i

# target to preprocess a source file
core/src/json.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/json.c.i
.PHONY : core/src/json.c.i

core/src/json.s: core/src/json.c.s
.PHONY : core/src/json.s

# target to generate assembly for a file
core/src/json.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/json.c.s
.PHONY : core/src/json.c.s

core/src/live.o: core/src/live.c.o
.PHONY : core/src/live.o

# target to build an object file
core/src/live.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_core.dir/build.make CMakeFiles/restream_core.dir/core/src/live.c.o
.PHONY : core/src/live.c.o

core/src/live.i: core/src/live.c.i
.PHONY : core/src/live.i

# target to preprocess a source file
core/src/live.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_core.dir/build.make CMakeFiles/restream_core.dir/core/src/live.c.i
.PHONY : core/src/live.c.i

core/src/live.s: core/src/live.c.s
.PHONY : core/src/live.s

# target to generate assembly for a file
core/src/live.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_core.dir/build.make CMakeFiles/restream_core.dir/core/src/live.c.s
.PHONY : core/src/live.c.s

core/src/live_backoff.o: core/src/live_backoff.c.o
.PHONY : core/src/live_backoff.o

# target to build an object file
core/src/live_backoff.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/live_backoff.c.o
.PHONY : core/src/live_backoff.c.o

core/src/live_backoff.i: core/src/live_backoff.c.i
.PHONY : core/src/live_backoff.i

# target to preprocess a source file
core/src/live_backoff.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/live_backoff.c.i
.PHONY : core/src/live_backoff.c.i

core/src/live_backoff.s: core/src/live_backoff.c.s
.PHONY : core/src/live_backoff.s

# target to generate assembly for a file
core/src/live_backoff.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/live_backoff.c.s
.PHONY : core/src/live_backoff.c.s

core/src/live_window.o: core/src/live_window.c.o
.PHONY : core/src/live_window.o

# target to build an object file
core/src/live_window.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/live_window.c.o
.PHONY : core/src/live_window.c.o

core/src/live_window.i: core/src/live_window.c.i
.PHONY : core/src/live_window.i

# target to preprocess a source file
core/src/live_window.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/live_window.c.i
.PHONY : core/src/live_window.c.i

core/src/live_window.s: core/src/live_window.c.s
.PHONY : core/src/live_window.s

# target to generate assembly for a file
core/src/live_window.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/live_window.c.s
.PHONY : core/src/live_window.c.s

core/src/logo.o: core/src/logo.c.o
.PHONY : core/src/logo.o

# target to build an object file
core/src/logo.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/logo.c.o
.PHONY : core/src/logo.c.o

core/src/logo.i: core/src/logo.c.i
.PHONY : core/src/logo.i

# target to preprocess a source file
core/src/logo.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/logo.c.i
.PHONY : core/src/logo.c.i

core/src/logo.s: core/src/logo.c.s
.PHONY : core/src/logo.s

# target to generate assembly for a file
core/src/logo.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/logo.c.s
.PHONY : core/src/logo.c.s

core/src/m3u8.o: core/src/m3u8.c.o
.PHONY : core/src/m3u8.o

# target to build an object file
core/src/m3u8.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/m3u8.c.o
.PHONY : core/src/m3u8.c.o

core/src/m3u8.i: core/src/m3u8.c.i
.PHONY : core/src/m3u8.i

# target to preprocess a source file
core/src/m3u8.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/m3u8.c.i
.PHONY : core/src/m3u8.c.i

core/src/m3u8.s: core/src/m3u8.c.s
.PHONY : core/src/m3u8.s

# target to generate assembly for a file
core/src/m3u8.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/m3u8.c.s
.PHONY : core/src/m3u8.c.s

core/src/metrics.o: core/src/metrics.c.o
.PHONY : core/src/metrics.o

# target to build an object file
core/src/metrics.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/metrics.c.o
.PHONY : core/src/metrics.c.o

core/src/metrics.i: core/src/metrics.c.i
.PHONY : core/src/metrics.i

# target to preprocess a source file
core/src/metrics.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/metrics.c.i
.PHONY : core/src/metrics.c.i

core/src/metrics.s: core/src/metrics.c.s
.PHONY : core/src/metrics.s

# target to generate assembly for a file
core/src/metrics.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/metrics.c.s
.PHONY : core/src/metrics.c.s

core/src/netmatch.o: core/src/netmatch.c.o
.PHONY : core/src/netmatch.o

# target to build an object file
core/src/netmatch.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/netmatch.c.o
.PHONY : core/src/netmatch.c.o

core/src/netmatch.i: core/src/netmatch.c.i
.PHONY : core/src/netmatch.i

# target to preprocess a source file
core/src/netmatch.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/netmatch.c.i
.PHONY : core/src/netmatch.c.i

core/src/netmatch.s: core/src/netmatch.c.s
.PHONY : core/src/netmatch.s

# target to generate assembly for a file
core/src/netmatch.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/netmatch.c.s
.PHONY : core/src/netmatch.c.s

core/src/nm3u8dlre.o: core/src/nm3u8dlre.c.o
.PHONY : core/src/nm3u8dlre.o

# target to build an object file
core/src/nm3u8dlre.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/nm3u8dlre.c.o
.PHONY : core/src/nm3u8dlre.c.o

core/src/nm3u8dlre.i: core/src/nm3u8dlre.c.i
.PHONY : core/src/nm3u8dlre.i

# target to preprocess a source file
core/src/nm3u8dlre.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/nm3u8dlre.c.i
.PHONY : core/src/nm3u8dlre.c.i

core/src/nm3u8dlre.s: core/src/nm3u8dlre.c.s
.PHONY : core/src/nm3u8dlre.s

# target to generate assembly for a file
core/src/nm3u8dlre.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/nm3u8dlre.c.s
.PHONY : core/src/nm3u8dlre.c.s

core/src/panel.o: core/src/panel.c.o
.PHONY : core/src/panel.o

# target to build an object file
core/src/panel.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/panel.c.o
.PHONY : core/src/panel.c.o

core/src/panel.i: core/src/panel.c.i
.PHONY : core/src/panel.i

# target to preprocess a source file
core/src/panel.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/panel.c.i
.PHONY : core/src/panel.c.i

core/src/panel.s: core/src/panel.c.s
.PHONY : core/src/panel.s

# target to generate assembly for a file
core/src/panel.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/panel.c.s
.PHONY : core/src/panel.c.s

core/src/random.o: core/src/random.c.o
.PHONY : core/src/random.o

# target to build an object file
core/src/random.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/random.c.o
.PHONY : core/src/random.c.o

core/src/random.i: core/src/random.c.i
.PHONY : core/src/random.i

# target to preprocess a source file
core/src/random.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/random.c.i
.PHONY : core/src/random.c.i

core/src/random.s: core/src/random.c.s
.PHONY : core/src/random.s

# target to generate assembly for a file
core/src/random.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/random.c.s
.PHONY : core/src/random.c.s

core/src/script.o: core/src/script.c.o
.PHONY : core/src/script.o

# target to build an object file
core/src/script.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/script.c.o
.PHONY : core/src/script.c.o

core/src/script.i: core/src/script.c.i
.PHONY : core/src/script.i

# target to preprocess a source file
core/src/script.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/script.c.i
.PHONY : core/src/script.c.i

core/src/script.s: core/src/script.c.s
.PHONY : core/src/script.s

# target to generate assembly for a file
core/src/script.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/script.c.s
.PHONY : core/src/script.c.s

core/src/server.o: core/src/server.c.o
.PHONY : core/src/server.o

# target to build an object file
core/src/server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_core.dir/build.make CMakeFiles/restream_core.dir/core/src/server.c.o
.PHONY : core/src/server.c.o

core/src/server.i: core/src/server.c.i
.PHONY : core/src/server.i

# target to preprocess a source file
core/src/server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_core.dir/build.make CMakeFiles/restream_core.dir/core/src/server.c.i
.PHONY : core/src/server.c.i

core/src/server.s: core/src/server.c.s
.PHONY : core/src/server.s

# target to generate assembly for a file
core/src/server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_core.dir/build.make CMakeFiles/restream_core.dir/core/src/server.c.s
.PHONY : core/src/server.c.s

core/src/state.o: core/src/state.c.o
.PHONY : core/src/state.o

# target to build an object file
core/src/state.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/state.c.o
.PHONY : core/src/state.c.o

core/src/state.i: core/src/state.c.i
.PHONY : core/src/state.i

# target to preprocess a source file
core/src/state.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/state.c.i
.PHONY : core/src/state.c.i

core/src/state.s: core/src/state.c.s
.PHONY : core/src/state.s

# target to generate assembly for a file
core/src/state.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/state.c.s
.PHONY : core/src/state.c.s

core/src/sysstats.o: core/src/sysstats.c.o
.PHONY : core/src/sysstats.o

# target to build an object file
core/src/sysstats.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/sysstats.c.o
.PHONY : core/src/sysstats.c.o

core/src/sysstats.i: core/src/sysstats.c.i
.PHONY : core/src/sysstats.i

# target to preprocess a source file
core/src/sysstats.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/sysstats.c.i
.PHONY : core/src/sysstats.c.i

core/src/sysstats.s: core/src/sysstats.c.s
.PHONY : core/src/sysstats.s

# target to generate assembly for a file
core/src/sysstats.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/sysstats.c.s
.PHONY : core/src/sysstats.c.s

core/src/url.o: core/src/url.c.o
.PHONY : core/src/url.o

# target to build an object file
core/src/url.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/url.c.o
.PHONY : core/src/url.c.o

core/src/url.i: core/src/url.c.i
.PHONY : core/src/url.i

# target to preprocess a source file
core/src/url.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/url.c.i
.PHONY : core/src/url.c.i

core/src/url.s: core/src/url.c.s
.PHONY : core/src/url.s

# target to generate assembly for a file
core/src/url.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_base.dir/build.make CMakeFiles/restream_base.dir/core/src/url.c.s
.PHONY : core/src/url.c.s

core/tests/selftest_main.o: core/tests/selftest_main.c.o
.PHONY : core/tests/selftest_main.o

# target to build an object file
core/tests/selftest_main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_selftest.dir/build.make CMakeFiles/restream_selftest.dir/core/tests/selftest_main.c.o
.PHONY : core/tests/selftest_main.c.o

core/tests/selftest_main.i: core/tests/selftest_main.c.i
.PHONY : core/tests/selftest_main.i

# target to preprocess a source file
core/tests/selftest_main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_selftest.dir/build.make CMakeFiles/restream_selftest.dir/core/tests/selftest_main.c.i
.PHONY : core/tests/selftest_main.c.i

core/tests/selftest_main.s: core/tests/selftest_main.c.s
.PHONY : core/tests/selftest_main.s

# target to generate assembly for a file
core/tests/selftest_main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/restream_selftest.dir/build.make CMakeFiles/restream_selftest.dir/core/tests/selftest_main.c.s
.PHONY : core/tests/selftest_main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... restream_base"
	@echo "... restream_core"
	@echo "... restream_selftest"
	@echo "... restreamair-server"
	@echo "... apps/server/main.o"
	@echo "... apps/server/main.i"
	@echo "... apps/server/main.s"
	@echo "... apps/server/net.o"
	@echo "... apps/server/net.i"
	@echo "... apps/server/net.s"
	@echo "... apps/server/probe.o"
	@echo "... apps/server/probe.i"
	@echo "... apps/server/probe.s"
	@echo "... apps/server/rs_dash.o"
	@echo "... apps/server/rs_dash.i"
	@echo "... apps/server/rs_dash.s"
	@echo "... core/deps/cJSON.o"
	@echo "... core/deps/cJSON.i"
	@echo "... core/deps/cJSON.s"
	@echo "... core/deps/mongoose.o"
	@echo "... core/deps/mongoose.i"
	@echo "... core/deps/mongoose.s"
	@echo "... core/src/aes.o"
	@echo "... core/src/aes.i"
	@echo "... core/src/aes.s"
	@echo "... core/src/audio_delay.o"
	@echo "... core/src/audio_delay.i"
	@echo "... core/src/audio_delay.s"
	@echo "... core/src/auth.o"
	@echo "... core/src/auth.i"
	@echo "... core/src/auth.s"
	@echo "... core/src/cdm.o"
	@echo "... core/src/cdm.i"
	@echo "... core/src/cdm.s"
	@echo "... core/src/cenc.o"
	@echo "... core/src/cenc.i"
	@echo "... core/src/cenc.s"
	@echo "... core/src/common.o"
	@echo "... core/src/common.i"
	@echo "... core/src/common.s"
	@echo "... core/src/crypto.o"
	@echo "... core/src/crypto.i"
	@echo "... core/src/crypto.s"
	@echo "... core/src/ffargs.o"
	@echo "... core/src/ffargs.i"
	@echo "... core/src/ffargs.s"
	@echo "... core/src/hls_decrypt.o"
	@echo "... core/src/hls_decrypt.i"
	@echo "... core/src/hls_decrypt.s"
	@echo "... core/src/json.o"
	@echo "... core/src/json.i"
	@echo "... core/src/json.s"
	@echo "... core/src/live.o"
	@echo "... core/src/live.i"
	@echo "... core/src/live.s"
	@echo "... core/src/live_backoff.o"
	@echo "... core/src/live_backoff.i"
	@echo "... core/src/live_backoff.s"
	@echo "... core/src/live_window.o"
	@echo "... core/src/live_window.i"
	@echo "... core/src/live_window.s"
	@echo "... core/src/logo.o"
	@echo "... core/src/logo.i"
	@echo "... core/src/logo.s"
	@echo "... core/src/m3u8.o"
	@echo "... core/src/m3u8.i"
	@echo "... core/src/m3u8.s"
	@echo "... core/src/metrics.o"
	@echo "... core/src/metrics.i"
	@echo "... core/src/metrics.s"
	@echo "... core/src/netmatch.o"
	@echo "... core/src/netmatch.i"
	@echo "... core/src/netmatch.s"
	@echo "... core/src/nm3u8dlre.o"
	@echo "... core/src/nm3u8dlre.i"
	@echo "... core/src/nm3u8dlre.s"
	@echo "... core/src/panel.o"
	@echo "... core/src/panel.i"
	@echo "... core/src/panel.s"
	@echo "... core/src/random.o"
	@echo "... core/src/random.i"
	@echo "... core/src/random.s"
	@echo "... core/src/script.o"
	@echo "... core/src/script.i"
	@echo "... core/src/script.s"
	@echo "... core/src/server.o"
	@echo "... core/src/server.i"
	@echo "... core/src/server.s"
	@echo "... core/src/state.o"
	@echo "... core/src/state.i"
	@echo "... core/src/state.s"
	@echo "... core/src/sysstats.o"
	@echo "... core/src/sysstats.i"
	@echo "... core/src/sysstats.s"
	@echo "... core/src/url.o"
	@echo "... core/src/url.i"
	@echo "... core/src/url.s"
	@echo "... core/tests/selftest_main.o"
	@echo "... core/tests/selftest_main.i"
	@echo "... core/tests/selftest_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

