// GENERATED by scripts/embed-assets.sh — do not edit by hand.
// Embeds public/ so the binary serves the web UI with no external files.
//
// This committed copy is an empty stub: local `swiftc` builds serve public/
// from disk (see servePublic), so they don't need the embedded assets. CI runs
// scripts/embed-assets.sh before compiling to fill this in for the release
// single-file binary.
enum PublicAssets {
    /// Web-asset relative path -> base64-encoded file contents.
    static let files: [String: String] = [:]
}
