#!/bin/sh
# Regenerates PublicAssets.swift by embedding every file under public/ (as
# base64) into the binary, so a standalone single-file build serves the web UI
# with no public/ directory on disk. Run from the repo root; CI runs it before
# compiling. Local dev doesn't need it — servePublic serves public/ from disk
# when present and only falls back to the embedded copy otherwise.
set -e
cd "$(dirname "$0")/.."
OUT=PublicAssets.swift

{
  echo "// GENERATED by scripts/embed-assets.sh — do not edit by hand."
  echo "// Embeds public/ so the binary serves the web UI with no external files."
  echo "enum PublicAssets {"
  echo "    /// Web-asset relative path -> base64-encoded file contents."
  echo "    static let files: [String: String] = ["
  find public -type f ! -name '.DS_Store' ! -path 'public/runtime/*' | LC_ALL=C sort | while IFS= read -r f; do
    rel=${f#public/}
    b64=$(base64 < "$f" | tr -d '\n')
    printf '        "%s": "%s",\n' "$rel" "$b64"
  done
  echo "    ]"
  echo "}"
} > "$OUT"

echo "wrote $OUT ($(wc -c < "$OUT" | tr -d ' ') bytes, $(grep -c ': "' "$OUT") files)"
