#!/usr/bin/env python3
"""Freezes the Swift reference output into core/tests/goldens.h.

The C self-test has to assert against something, and the thing worth asserting
against is what the Swift implementations actually produce — they are what the
app ships today. This reads the dump written by scripts/dump-goldens.swift and
emits it as C literals, so the self-test needs no Swift toolchain to run:

    swiftc M3U8Rewriter.swift FFmpegResident.swift CoreParityFixtures.swift \\
        scripts/dump-goldens.swift -o /tmp/dump-goldens
    /tmp/dump-goldens | python3 scripts/gen-goldens.py

CoreParityTest.swift re-runs the same comparison live on every `restreamair
selftest`, so a golden that drifts away from Swift cannot go unnoticed.
"""

import os
import sys


def unescape(s):
    out = []
    i = 0
    while i < len(s):
        if s[i] == "\\" and i + 1 < len(s):
            nxt = s[i + 1]
            if nxt == "n":
                out.append("\n")
            elif nxt == "r":
                out.append("\r")
            elif nxt == "t":
                out.append("\t")
            elif nxt == "\\":
                out.append("\\")
            else:
                out.append(s[i])
                out.append(nxt)
            i += 2
            continue
        out.append(s[i])
        i += 1
    return "".join(out)


def c_string(s):
    # Iterates UTF-8 bytes, not code points: a C string literal is a byte
    # sequence, and emitting "\u00e9" as one \351 byte would hand the C code
    # Latin-1 where Swift produced UTF-8.
    out = ['"']
    for byte in s.encode("utf-8"):
        ch = chr(byte)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append('\\n"\n    "')
        elif ch == "\t":
            out.append("\\t")
        elif byte < 0x20 or byte > 0x7E:
            # Octal, not hex: a hex escape has no length limit, so "\\x1f"
            # followed by a digit would be read as one enormous character.
            out.append("\\%03o" % byte)
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


entries = []
for line in sys.stdin.read().split("\n"):
    if not line:
        continue
    key, _, value = line.partition("\t")
    entries.append((key, unescape(value)))

lines = [
    "// Generated by scripts/gen-goldens.py — do not edit by hand.",
    "// The output the Swift implementations in M3U8Rewriter.swift and",
    "// FFmpegResident.swift produce for the fixtures in fixtures.h, frozen so the C",
    "// self-test can check itself against the behaviour the app ships today.",
    "",
    "#ifndef RS_GOLDENS_H",
    "#define RS_GOLDENS_H",
    "",
    "typedef struct {",
    "    const char *key;",
    "    const char *value;",
    "} rs_golden;",
    "",
    "static const rs_golden rs_goldens[] = {",
]
for key, value in entries:
    lines.append("    {%s," % c_string(key))
    lines.append("     %s}," % c_string(value))
lines.append("};")
lines.append("")
lines.append("#endif  // RS_GOLDENS_H")
lines.append("")

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
path = os.path.join(root, "core", "tests", "goldens.h")
with open(path, "w") as handle:
    handle.write("\n".join(lines))
print("wrote core/tests/goldens.h (%d goldens)" % len(entries))
