// Generated by scripts/gen-fixtures.py — do not edit by hand.
// Input for the C self-test, kept in one table so a case can be added without
// hand-escaping it into a header.


#ifndef RS_FIXTURES_H
#define RS_FIXTURES_H

#include "rs_ffargs.h"

typedef struct {
    const char *name;
    const char *base;
    const char *text;
} rs_playlist_fixture;

static const rs_playlist_fixture rs_playlist_fixtures[] = {
    {"media", "https://origin.example.com/live/hls/media.m3u8",
     "#EXTM3U\n"
    "#EXT-X-VERSION:6\n"
    "#EXT-X-TARGETDURATION:4\n"
    "#EXT-X-MEDIA-SEQUENCE:42\n"
    "#EXT-X-KEY:METHOD=AES-128,URI=\"key.bin\",IV=0x0123456789abcdef0123456789abcdef\n"
    "#EXT-X-MAP:URI=\"init.mp4\"\n"
    "\n"
    "#EXTINF:4.000,\n"
    "seg1.m4s\n"
    "#EXTINF:4.000,\n"
    "./sub/seg2.m4s\n"
    "#EXTINF:4.000,\n"
    "../up/seg3.m4s\n"
    "#EXTINF:4.000,\n"
    "/rooted/seg4.m4s\n"
    "#EXTINF:4.000,\n"
    "https://cdn.example.com/abs/seg5.m4s\n"
    "#EXTINF:4.000,\n"
    "  spaced/seg6.m4s  \n"
    "#EXTINF:4.000,\n"
    "seg 7.m4s\n"
    "#EXT-X-ENDLIST\n"
    ""},
    {"media_plain", "https://origin.example.com/a/b/c.m3u8",
     "#EXTM3U\n"
    "#EXTINF:2.000,\n"
    "s0.ts\n"
    "#EXT-X-KEY:METHOD=AES-128,URI=\"https://keys.example.com/k?id=1\"\n"
    "#EXTINF:2.000,\n"
    "s1.ts\n"
    ""},
    {"master", "https://origin.example.com/live/master.m3u8",
     "#EXTM3U\n"
    "#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID=\"aac\",NAME=\"English\",LANGUAGE=\"en\",DEFAULT=YES,URI=\"audio/en.m3u8\"\n"
    "#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID=\"aac\",NAME=\"Commentary, extended\",URI=\"audio/cm.m3u8\"\n"
    "#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID=\"subs\",NAME=\"English\",URI=\"subs/en.m3u8\"\n"
    "#EXT-X-STREAM-INF:BANDWIDTH=1280000,RESOLUTION=1280x720,CODECS=\"avc1.4d401f,mp4a.40.2\",AUDIO=\"aac\"\n"
    "720p/index.m3u8\n"
    "#EXT-X-STREAM-INF:BANDWIDTH=2560000,RESOLUTION=1920x1080,CODECS=\"avc1.640028,mp4a.40.2\",AUDIO=\"aac\"\n"
    "https://cdn.example.com/1080p/index.m3u8\n"
    "#EXT-X-STREAM-INF:BANDWIDTH=400000\n"
    "audio-only.m3u8\n"
    ""},
    {"master_tail", "https://origin.example.com/live/master.m3u8",
     "#EXTM3U\n"
    "#EXT-X-STREAM-INF:BANDWIDTH=100"},
};

static const char *const rs_ff2_ids[] = {"v1", "v2", "a1"};
static const char *const rs_ff2_types[] = {"video", "video", "audio"};
static const char *const rs_ff3_ids[] = {"v1", "a1"};
static const char *const rs_ff3_types[] = {"video", "audio"};

static const char *const rs_ffargs_case_names[] = {
    "ts-hls",
    "fmp4-hls-with-headers-and-key",
    "multi-ts-hls",
    "multi-ts-hls-single-video",
    "resident-srt-server-bare-port",
    "resident-srt-server-empty-port",
    "resident-udp-push",
    "resident-custom-quoted",
};

static const rs_ffargs_inputs rs_ffargs_cases[] = {
    {
        "https://origin.example.com/live/stream.m3u8", "m3u8", "ffmpegTsHls",
        "hls", "",
        "",
        "",
        "", "",
        NULL, 0, NULL, NULL, 0,
        "/tmp/restreamair-fixture", "/tmp/restreamair-fixture/live.m3u8", 6, 4,
    },
    {
        "https://origin.example.com/live/stream.mpd", "mpd", "ffmpegFmp4Hls",
        "hls", "",
        "  \n"
    "abcdef0123456789abcdef0123456789:00112233445566778899aabbccddeeff\n"
    "",
        "User-Agent: ReStreamAir/1.0\n"
    "\n"
    "  Referer: https://example.com  \n"
    "",
        "http://127.0.0.1:8888", " ?token=abc&region=eu ",
        NULL, 0, NULL, NULL, 0,
        "/tmp/restreamair-fixture", "/tmp/restreamair-fixture/live.m3u8", 6, 4,
    },
    {
        "https://origin.example.com/live/stream.mpd", "mpd", "ffmpegMultiTsHls",
        "hls", "",
        "00112233445566778899aabbccddeeff",
        "",
        "", "",
        rs_ff2_ids, 3, rs_ff2_ids, rs_ff2_types, 3,
        "/tmp/restreamair-fixture", "/tmp/restreamair-fixture/live.m3u8", 6, 4,
    },
    {
        "https://origin.example.com/live/stream.mpd", "mpd", "ffmpegMultiTsHls",
        "hls", "",
        "",
        "",
        "", "",
        rs_ff3_ids, 2, rs_ff3_ids, rs_ff3_types, 2,
        "/tmp/restreamair-fixture", "/tmp/restreamair-fixture/live.m3u8", 6, 4,
    },
    {
        "https://origin.example.com/live/stream.mpd", "mpd", "ffmpegResident",
        "srtServer", "9100",
        "",
        "",
        "", "",
        NULL, 0, NULL, NULL, 0,
        "/tmp/restreamair-fixture", "/tmp/restreamair-fixture/live.m3u8", 6, 4,
    },
    {
        "https://origin.example.com/live/stream.mpd", "mpd", "ffmpegResident",
        "srtServer", "",
        "",
        "",
        "", "",
        NULL, 0, NULL, NULL, 0,
        "/tmp/restreamair-fixture", "/tmp/restreamair-fixture/live.m3u8", 6, 4,
    },
    {
        "rtmp://origin.example.com/live/stream", "mpd", "ffmpegResident",
        "udpSrt", "udp://239.0.0.1:1234?pkt_size=1316",
        "",
        "",
        "", "ignored=1",
        NULL, 0, NULL, NULL, 0,
        "/tmp/restreamair-fixture", "/tmp/restreamair-fixture/live.m3u8", 6, 4,
    },
    {
        "https://origin.example.com/live/stream.m3u8?a=1", "m3u8", "ffmpegResident",
        "custom", "-f flv 'rtmp://a.example.com/app/key with spaces' -metadata title=\"My Stream\"",
        ":deadbeefdeadbeefdeadbeefdeadbeef",
        "",
        "", "&more=2",
        NULL, 0, NULL, NULL, 0,
        "/tmp/restreamair-fixture", "/tmp/restreamair-fixture/live.m3u8", 6, 4,
    },
};

#endif  // RS_FIXTURES_H
